using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DB
{
    public class DB
    {
        public static List<Digimon> Digimons = new List<Digimon>()
        {
          new Digimon ("Агумон","Agumon",Form.New),
          new Digimon ("Аирдрамон","Airdramon",Form.Champ),
          new Digimon ("АйсДевимон","IceDevimon",Form.Champ),
          new Digimon ("Айсмон","Icemon",Form.Champ),
          new Digimon ("Акаторимон","Akatorimon",Form.Champ),
          new Digimon ("Ангевомон","Angewomon",Form.High),
          new Digimon ("Ангемон","Angemon",Form.Champ),
          new Digimon ("Андромон","Andromon",Form.High),
          new Digimon ("АэроВиидрамон","AeroVeedramon",Form.High),
          new Digimon ("Баихумон","Baihumon",Form.Mega),
          new Digimon ("Бакемон","Bakemon",Form.Champ),
          new Digimon ("Бёрдрамон","Birdramon",Form.Champ),
          new Digimon ("Бетамон","Betamon",Form.New),
          new Digimon ("Блоссомон","Blossomon",Form.High),
          new Digimon ("БлюзМерамон","Blue Meramon",Form.High),
          new Digimon ("БойГреймон","WarGreymon",Form.Mega),
          new Digimon ("Болтмон","Boltmon",Form.Mega),
          new Digimon ("Вадемон","Vademon",Form.High),
          new Digimon ("ВаруМонзаемон","WaruMonzaemon",Form.High),
          new Digimon ("ВаруСидрамон","WaruSeadramon",Form.High),
          new Digimon ("Вегиемон","Vegiemon",Form.Champ),
          new Digimon ("ВеномМиотисмон","VenomMyotismon",Form.Mega),
          new Digimon ("ВереГарурумон","WereGarurumon",Form.High),
          new Digimon ("Вермилимон","Vermilimon",Form.High),
          new Digimon ("Визардмон","Wizardmon",Form.Champ),
          new Digimon ("Виидрамон","Veedramon",Form.Champ),
          new Digimon ("Виимон","Veemon",Form.New),
          new Digimon ("Вудмон","Woodmon",Form.Champ),
          new Digimon ("Габумон","Gabumon",Form.New),
          new Digimon ("Гайа","Gaia",Form.Mega),
          new Digimon ("Гарудамон","Garudamon",Form.High),
          new Digimon ("Газимон","Gazimon",Form.New),
          new Digimon ("Гарбамон","Garbagemon",Form.High),
          new Digimon ("Гарурумон","Garurumon",Form.Champ),
          new Digimon ("Гатомон","Gatomon",Form.Champ),
          new Digimon ("Гвардромон","Guardromon",Form.Champ),
          new Digimon ("Гекомон","Gekomon",Form.Champ),
          new Digimon ("Гесомон","Gesomon",Form.Champ),
          new Digimon ("Гигадрамон","Gigadramon",Form.High),
          new Digimon ("Гизамон","Gizamon",Form.New),
          new Digimon ("Гиромон","Giromon",Form.High),
          new Digimon ("Гобуримон","Goburimon",Form.New),
          new Digimon ("ГолдКабутеримон","GoldKabuterimon",Form.Mega),
          new Digimon ("Гомамон","Gomamon",Form.New),
          new Digimon ("Гоцумон","Gotsumon",Form.New),
          new Digimon ("ГранКувагамон","GranKuwagamon",Form.Mega),
          new Digimon ("Греймон","Greymon",Form.Champ),
          new Digimon ("Грифонмон","Gryphonmon",Form.Mega),
          new Digimon ("Гурурумон","Gururumon",Form.Champ),
          new Digimon ("ДаркРизамон","DarkLizardmon",Form.Champ),
          new Digimon ("ДаркТираномон","DarkTyrannomon",Form.Champ),
          new Digimon ("Датамон","Datamon",Form.High),
          new Digimon ("Девидрамон","Devidramon",Form.Champ),
          new Digimon ("Девимон","Devimon",Form.Champ),
          new Digimon ("Дельтамон","Deltamon",Form.Champ),
          new Digimon ("ДемиДевимон","DemiDevimon",Form.New),
          new Digimon ("Дерамон","Deramon",Form.High),
          new Digimon ("Диаборомон","Diaboromon",Form.Mega),
          new Digimon ("Дигитамамон","Digitamamon",Form.High),
          new Digimon ("Докунемон","Dokunemon",Form.New),
          new Digimon ("Дольфмон","Dolphmon",Form.Champ),
          new Digimon ("Драгомон","Dragomon",Form.High),
          new Digimon ("Дримогемон","Drimogemon",Form.High),
          new Digimon ("Ж-Моджамон","Jungle Mojyamon",Form.Champ),
          new Digimon ("Жижимон","Jijimon",Form.Mega),
          new Digimon ("Зудомон","Zudomon",Form.High),
          new Digimon ("Иккакумон","Ikkakumon",Form.Champ),
          new Digimon ("Империалдрамон","Imperialdramon",Form.Mega),
          new Digimon ("Кабутеримон","Kabuterimon",Form.Champ),
          new Digimon ("Кентарумон","Centarumon",Form.Champ),
          new Digimon ("Кивимон","Kiwimon",Form.Champ),
          new Digimon ("Кимерамон","Kimeramon",Form.Mega),
          new Digimon ("КлирАгумон","ClearAgumon",Form.New),
          new Digimon ("Клокмон","Clockmon",Form.Champ),
          new Digimon ("Коеламон","Coelamon",Form.Champ),
          new Digimon ("Кокаторимон","Kokatorimon",Form.Champ),
          new Digimon ("Крабмон","Crabmon",Form.New),
          new Digimon ("Кувагамон","Kuwagamon",Form.Champ),
          new Digimon ("Кунемон","Kunemon",Form.New),
          new Digimon ("Кэндлмон","Candlemon",Form.New),
          new Digimon ("Левая рука Гайа","Gaia left hand",Form.Mega),
          new Digimon ("Леомон","Leomon",Form.Champ),
          new Digimon ("Лилимон","Lillymon",Form.High),
          new Digimon ("Лорд Хаоса","ChaosLord",Form.Mega),
          new Digimon ("МагнаАнгемон","MagnaAngemon",Form.High),
          new Digimon ("Магнадрамон","Magnadramon",Form.Mega),
          new Digimon ("Мамемон","Mamemon",Form.High),
          new Digimon ("Мамонтмон","Mamothmon",Form.High),
          new Digimon ("МаринеАнгемон","MarineAngemon",Form.Mega),
          new Digimon ("МаринеДевимон","MarineDevimon",Form.High),
          new Digimon ("МастерТираномон","MasterTyrannomon",Form.High),
          new Digimon ("Машинедрамон","Macinedramon",Form.Mega),
          new Digimon ("Машрумон","Mushroomon",Form.New),
          new Digimon ("Мегадрамон","Megadramon",Form.High),
          new Digimon ("МегаКабутеримон","MegaKabuterimon",Form.High),
          new Digimon ("МегаСидрамон","MegaSeadramon",Form.High),
          new Digimon ("Мерамон","Meramon",Form.Champ),
          new Digimon ("МеталГарурумон","MetalGarurumon",Form.Mega),
          new Digimon ("МеталГреймон","MetalGreymon",Form.High),
          new Digimon ("МеталМамемон","MetalMamemon",Form.High),
          new Digimon ("МеталСидрамон","MetalSeadramon",Form.Mega),
          new Digimon ("МеталТираномон","MetalTyrannomon",Form.High),
          new Digimon ("МеталЭтемон","MetalEtemon",Form.Mega),
          new Digimon ("Метеормон","Meteormon",Form.High),
          new Digimon ("Миотисмон","Myotismon",Form.High),
          new Digimon ("Моджамон","Mojyamon",Form.Champ),
          new Digimon ("Монзаемон","Monzaemon",Form.High),
          new Digimon ("Монохромон","Monochromon",Form.Champ),
          new Digimon ("МориШеллмон","MoriShellmon",Form.Champ),
          new Digimon ("МудФригимон","MudFrigimon",Form.Champ),
          new Digimon ("НайсДримогемон","NiseDrimogemon",Form.Champ),
          new Digimon ("Нанимон","Nanimon",Form.Champ),
          new Digimon ("Неокримсон","NeoCrimson",Form.Mega),
          new Digimon ("Нинидзямон","Ninjamon",Form.Champ),
          new Digimon ("Нумемон","Numemon",Form.Champ),
          new Digimon ("Оверлорд Гайа","Overlord Gaia",Form.Mega),
          new Digimon ("Огремон","Ogremon",Form.Champ),
          new Digimon ("Октомон","Octomon",Form.Champ),
          new Digimon ("Окувамон","Okuwamon",Form.High),
          new Digimon ("Омнимон","Omnimon",Form.Mega),
          new Digimon ("Отамамон","Otamamon",Form.New),
          new Digimon ("П-Сукамон","Platinum Sukamon",Form.Champ),
          new Digimon ("Палмон","Palmon",Form.New),
          new Digimon ("Панджамон","Panjamon",Form.High),
          new Digimon ("Паппетмон","Puppetmon",Form.Mega),
          new Digimon ("Патамон","Patamon",Form.New),
          new Digimon ("Пиддомон","Piddomon",Form.Champ),
          new Digimon ("Пиёмон","Biyomon",Form.New),
          new Digimon ("Пиксимон","Piximon",Form.High),
          new Digimon ("Пингвимон","Penguinmon",Form.New),
          new Digimon ("Правая рука Гайа","Gaia right hand",Form.Mega),
          new Digimon ("Пречиомон","Plesiomon",Form.Mega),
          new Digimon ("ПринцМамемон","PrinceMamemon",Form.Mega),
          new Digimon ("Пукумон","Pukumon",Form.Mega),
          new Digimon ("Пьерротмон","Piedmon",Form.Mega),
          new Digimon ("Раидрамон","Raidramon",Form.High),
          new Digimon ("Раремон","Raremon",Form.Champ),
          new Digimon ("РедВегиемон","RedVegiemon",Form.Champ),
          new Digimon ("Роземон","Rosemon",Form.Mega),
          new Digimon ("Сабердрамон","Saberdramon",Form.Champ),
          new Digimon ("СаберЛеомон","SaberLeomon",Form.Mega),
          new Digimon ("Серафимон","Seraphimon",Form.Mega),
          new Digimon ("Сидрамон","Seadramon",Form.Champ),
          new Digimon ("Сиякомон","Syakomon",Form.New),
          new Digimon ("Скорпиомон","Scorpiomon",Form.High),
          new Digimon ("СкуллМамонтмон","SkullMamothmon",Form.Mega),
          new Digimon ("СноуАгумон","SnowAgumon",Form.New),
          new Digimon ("СноуГобуримон","SnowGoburimon",Form.New),
          new Digimon ("Соулмон","Soulmon",Form.Champ),
          new Digimon ("Стармон","Starmon",Form.Champ),
          new Digimon ("Страж вакцины","Vaccine Guardian",Form.Mega),
          new Digimon ("Страж вируса","Virus Guardian",Form.Mega),
          new Digimon ("Страж данных","Data Guardian",Form.Mega),
          new Digimon ("Сукамон","Sukamon",Form.Champ),
          new Digimon ("СэндЯнмамон","SandYanmamon",Form.Champ),
          new Digimon ("Танкмон","Tankmon",Form.Champ),
          new Digimon ("Тапирмон","Tapirmon",Form.New),
          new Digimon ("Таскмон","Tuskmon",Form.Champ),
          new Digimon ("Теккамон","Tekkamon",Form.High),
          new Digimon ("Тентомон","Tentomon",Form.New),
          new Digimon ("Тинмон","Tinmon",Form.High),
          new Digimon ("Тираномон","Tyrannomon",Form.Champ),
          new Digimon ("Тогемон","Togemon",Form.Champ),
          new Digimon ("Тортомон","Tortomon",Form.Champ),
          new Digimon ("ТойАгумон","ToyAgumon",Form.New),
          new Digimon ("Трицерамон","Triceramon",Form.High),
          new Digimon ("Тыквинмон","Pumpkinmon",Form.High),
          new Digimon ("Увамон","Whamon",Form.High),
          new Digimon ("Унимон","Unimon",Form.High),
          new Digimon ("Фантомон","Phantomon",Form.High),
          new Digimon ("Фениксмон","Phoenixmon",Form.Mega),
          new Digimon ("ФлареРизамон","FlareLizardmon",Form.Champ),
          new Digimon ("Флеймдрамон","Flamedramon",Form.Champ),
          new Digimon ("Флимон","Flymon",Form.Champ),
          new Digimon ("Флорамон","Floramon",Form.New),
          new Digimon ("Фригимон","Frigimon",Form.Champ),
          new Digimon ("Хагурумон","Hagurumon",Form.New),
          new Digimon ("Хёгамон","Hyogamon",Form.Champ),
          new Digimon ("Циклонемон","Cyclonemon",Form.Champ),
          new Digimon ("Цукаимон","Tsukaimon",Form.New),
          new Digimon ("ЧерепМерамон","SkullMeramon",Form.High),
          new Digimon ("ЧерепоГреймон","SkullGreymon",Form.High),
          new Digimon ("Черримон","Cherrymon",Form.High),
          new Digimon ("Шеллмон","Shellmon",Form.Champ),
          new Digimon ("ШимаУнимон","ShimaUnimon",Form.Champ),
          new Digimon ("ШоганГекомон","ShogunGekomon",Form.High),
          new Digimon ("Эйпмон","Apemon",Form.Champ),
          new Digimon ("ЭксТираномон","ExTyrannomon",Form.High),
          new Digimon ("Элекмон","Elecmon",Form.New),
          new Digimon ("Этемон","Etemon",Form.High),
          new Digimon ("Янмамон","Yanmamon",Form.Champ),
        };

    }

    public class Digimon
    {
        public Digimon(string nameRus, string nameEng, Form form)
        {
            NameEng = nameEng;
            NameRus = nameRus;
            Form = form;
        }

        public string Id => NameEng;

        public string NameEng { get; set; }

        public string NameRus { get; set; }

        public Form Form { get; set; }

    }

    public enum Form
    {
        New = 0,
        Champ = 1,
        High = 2,
        Mega = 3
    }


}
